# File: .github/workflows/deploy.yml
name: 🚀 Build & Deploy All Clients

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout code
      - uses: actions/checkout@v4

      # 2) Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Build *all clients except* landingpage
      - name: Build client demos
        run: |
          for dir in project/*/ ; do
            slug=$(basename "$dir")
            if [ "$slug" = "landingpage" ]; then
              continue
            fi
            echo "🔨 Building demo: $slug"
            cd "$dir"
            npm ci
            npm run build
            cd ../../
            rm -rf "$slug"
            mkdir -p "$slug"
            cp -r "project/$slug/dist/." "$slug/"
            # Per-client SPA fallback:
            cp "$slug/index.html" "$slug/404.html"
          done

      # 4) Build & copy the landing page into root
      - name: Build landing page
        run: |
          cd project/landingpage
          npm ci
          npm run build
          cd ../../
          cp -r project/landingpage/dist/* .
          # Root SPA fallback:
          cp index.html 404.html

      # 5) (Optional) Debug listing
      - name: Show publish directory contents
        run: |
          echo "=== publish contents ==="
          ls -R .
          echo "========================"

      # 6) Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
