name: 🚀 Build & Deploy All Clients

on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your code
      - uses: actions/checkout@v4

      # 2) Setup Node.js (no root npm install)
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Build every folder under project/
      - name: Build all clients
        run: |
          for dir in project/*/ ; do
            slug=$(basename "$dir")
            echo "🔨 Building $slug…"
            cd "$dir"
            npm ci
            npm run build
            cd ../../
            rm -rf "$slug"
            mkdir -p "$slug"
            cp -r "project/$slug/dist/." "$slug/"
          done

      # 4) Copy landing page
      - name: Copy landing page
        run: |
          # bring the built landing-page into root
          cp project/landingpage/dist/index.html ./index.html
          cp -r project/landingpage/dist/assets .

          # fix absolute URLs so they resolve correctly on your custom domain
          sed -i 's|src="/assets|src="assets|g' index.html
          sed -i 's|href="/assets|href="assets|g' index.html
          sed -i 's|href="/vite.svg|href="vite.svg|g' index.html

      # 5) Add domain & SPA fallback
      - name: Add CNAME & 404.html
        run: |
          cat > 404.html << 'EOF'
          <!DOCTYPE html>
          <html><head>
            <meta http-equiv="refresh" content="0; url=/" />
          </head><body>
            <p>Redirecting…</p>
          </body></html>
          EOF

      # 6) Deploy to GitHub Pages (defaults to gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./   # root now has index.html, /<slug>/ folders, assets/, 404.html, CNAME
          # publish_branch: gh-pages  # optional, defaults to gh-pages
