name: Build & Deploy All Sites

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # ────────────── Landing Page ──────────────
      - name: Build Landing Page
        run: |
          cd project/landingpage
          npm ci
          npm run build

      - name: Deploy Landing Page to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: project/landingpage/dist
          # "" means root of gh-pages branch
          destination_dir: ''
          # first publish wipes old content

      # ────────────── Anissaylaa ──────────────
      - name: Build Anissaylaa
        run: |
          cd project/anissaylaa
          npm ci
          npm run build

      - name: Deploy Anissaylaa to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: project/anissaylaa/dist
          destination_dir: anissaylaa
          keep_files: true    # preserve what landingpage pushed

      # ────────────── ThaiRiverside ──────────────
      - name: Build ThaiRiverside
        run: |
          cd project/thairiverside
          npm ci
          npm run build

      - name: Deploy ThaiRiverside to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: project/thairiverside/dist
          destination_dir: thairiverside
          keep_files: true

      # ────────────── ChickenMacAndMore ──────────────
      - name: Build ChickenMacAndMore
        run: |
          cd project/chickenmacandmore
          npm ci
          npm run build

      - name: Deploy ChickenMacAndMore to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: project/chickenmacandmore/dist
          destination_dir: chickenmacandmore
          keep_files: true
