name: Deploy Thai Riverside

on:
  push:
    branches: [main]
    paths:
      - 'project/thairiverside/**'
      - '.github/workflows/thairiverside-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: project/thairiverside

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Copy to deploy folder
        run: |
          mkdir -p $GITHUB_WORKSPACE/project/__deploy/thairiverside
          cp -a $GITHUB_WORKSPACE/project/thairiverside/dist/. $GITHUB_WORKSPACE/project/__deploy/thairiverside/

      - name: Debug - List deploy folder
        run: ls -al $GITHUB_WORKSPACE/project/__deploy/thairiverside

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: project/__deploy
