name: 🚀 Build & Deploy All Clients

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # Build each client demo (skip landingpage)
      - name: Build demos
        env:
          VITE_FREECUTS_CSV_URL: ${{ secrets.VITE_FREECUTS_CSV_URL }}
          VITE_SPECIALS_CSV: ${{ secrets.VITE_SPECIALS_CSV }}
          VITE_SNEAKERS_CSV: ${{ secrets.VITE_SNEAKERS_CSV }}
          VITE_SNEAKERS_PUBKEY: ${{ secrets.VITE_SNEAKERS_PUBKEY }}
          VITE_SNEAKERS_GID: ${{ secrets.VITE_SNEAKERS_GID }}
        run: |
          for dir in project/*/; do
            slug=$(basename "$dir")
            if [ "$slug" = "landingpage" ]; then
              continue
            fi
            echo "🔨 Building demo: $slug"
            cd "$dir"
            npm ci
            npm run build
            cd ../../

            rm -rf "$slug"
            mkdir -p "$slug"
            cp -r "project/$slug/dist/." "$slug/"
          done

      # Build & copy landing page into root
      - name: Build landing page
        env:
          VITE_FREECUTS_CSV_URL: ${{ secrets.VITE_FREECUTS_CSV_URL }}
          VITE_SPECIALS_CSV: ${{ secrets.VITE_SPECIALS_CSV }}
          VITE_SNEAKERS_CSV: ${{ secrets.VITE_SNEAKERS_CSV }}
          VITE_SNEAKERS_PUBKEY: ${{ secrets.VITE_SNEAKERS_PUBKEY }}
          VITE_SNEAKERS_GID: ${{ secrets.VITE_SNEAKERS_GID }}
        run: |
          cd project/landingpage
          npm ci
          npm run build
          cd ../../
          cp -r project/landingpage/dist/* .

      # Dynamic SPA fallback: send to demo folder only if that folder exists.
      # Otherwise treat as a root SPA route (e.g., /careers).
      - name: Create smart 404.html
        run: |
          SLUGS=()
          for d in */ ; do
            d="${d%/}"
            case "$d" in
              project|.git|.github|node_modules) continue ;;
            esac
            if [ -f "$d/index.html" ]; then
              SLUGS+=("$d")
            fi
          done
          printf -v SLUGS_JS "'%s'," "${SLUGS[@]}"
          SLUGS_JS="[${SLUGS_JS%,}]"

          cat > 404.html << EOF
          <!DOCTYPE html>
          <html>
          <head><meta charset="utf-8"><title>Redirecting…</title></head>
          <body>
            <script>
              (function () {
                const DEMO_SLUGS = ${SLUGS_JS};

                const raw = location.pathname.replace(/^\/+/, '');
                const parts = raw.split('/').filter(Boolean);
                const q = location.search || '';
                const h = location.hash || '';

                if (parts.length === 0) {
                  location.replace('/index.html' + q + h);
                  return;
                }

                const slug = parts[0];
                const rest = parts.slice(1).join('/');

                if (DEMO_SLUGS.includes(slug)) {
                  if (rest === '' || rest.startsWith('index.html') || rest.startsWith('404.html')) {
                    location.replace('/' + slug + '/index.html' + q + h);
                  } else {
                    location.replace('/' + slug + '/index.html#/' + rest + q + h);
                  }
                  return;
                }

                // Not a demo slug → root SPA route. Encode original path.
                const query = q ? '&q=' + q.slice(1).replace(/&/g, '~and~') : '';
                const p = '?p=/' + raw + query + h;
                location.replace('/' + p);
              })();
            </script>
            <p>Redirecting…</p>
          </body>
          </html>
          EOF

      - name: Show publish directory
        run: |
          echo "=== publish contents ==="
          ls -R .
          echo "========================"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./

      - name: Set Sneakers CSV Secrets
        run: |
          echo "VITE_SNEAKERS_CSV=${{ secrets.VITE_SNEAKERS_CSV }}" >> $GITHUB_ENV
          echo "VITE_SNEAKERS_PUBKEY=${{ secrets.VITE_SNEAKERS_PUBKEY }}" >> $GITHUB_ENV
          echo "VITE_SNEAKERS_GID=${{ secrets.VITE_SNEAKERS_GID }}" >> $GITHUB_ENV
