# File: .github/workflows/deploy.yml
name: 🚀 Build & Deploy All Clients

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repository
      - uses: actions/checkout@v4

      # 2) Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Build every client under project/
      - name: Build all clients
        run: |
          for dir in project/*/ ; do
            slug=$(basename "$dir")
            echo "🔨 Building $slug…"
            cd "$dir"
            npm ci
            npm run build
            cd ../../
            rm -rf "$slug"
            mkdir -p "$slug"
            cp -r "project/$slug/dist/." "$slug/"
          done

      # 4) Copy landing-page build output into repo root
      - name: Copy landing page
        run: |
          cp -r project/landingpage/dist/* .

      # 5) SPA fallback for deep links
      - name: Create 404.html fallback
        run: |
          cp index.html 404.html

      # 6) Debug: list everything that will be published
      - name: Show publish directory contents
        run: |
          echo "=== publish dir listing ==="
          ls -R .
          echo "=== end listing ==="

      # 7) Deploy to GitHub Pages (pushes to gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./   # root now has index.html, assets/, /<slug>/, 404.html, CNAME
