# File: .github/workflows/deploy.yml
name: 🚀 Build & Deploy All Clients

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the code
      - uses: actions/checkout@v4

      # 2) Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Build each folder under project/
      - name: Build all clients
        run: |
          for dir in project/*/ ; do
            slug=$(basename "$dir")
            echo "🔨 Building $slug…"
            cd "$dir"
            npm ci
            npm run build
            cd ../../
            rm -rf "$slug"
            mkdir -p "$slug"
            cp -r "project/$slug/dist/." "$slug/"
          done

      # 4) Copy landing-page build output to repo root
      - name: Copy landing page
        run: |
          cp -r project/landingpage/dist/* .

      # 5) Copy CNAME (so your custom domain stays set)
      - name: Copy CNAME
        run: cp CNAME .

      # 6) SPA fallback: serve index.html on 404 (deep links)
      - name: Fallback 404 → index.html
        run: cp index.html 404.html

      # 7) Debug (optional—remove after you confirm it works)
      - name: Show publish directory
        run: |
          echo "=== publish contents ==="
          ls -R .
          echo "========================"

      # 8) Deploy to GitHub Pages (gh-pages branch)
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
