name: 🚀 Build & Deploy All Clients

on:
  push:
    branches: [ main ]

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Install any shared devDependencies (optional)
      - run: npm ci

      # Find & build each project folder
      - name: Build all clients
        run: |
          for dir in project/*/ ; do
            slug=$(basename "$dir")
            echo "Building $slug…"
            cd "$dir"
            npm ci
            npm run build
            cd ../../
            rm -rf "$slug"
            mkdir -p "$slug"
            cp -r "project/$slug/dist/." "$slug/"
          done

      # Landing page goes to root
      - name: Copy landing page
        run: |
          cp project/landingpage/dist/index.html .
          cp -r project/landingpage/dist/assets .

      # Add CNAME + SPA fallback
      - run: |
          cp CNAME .
          cat > 404.html <<'EOF'
          <!DOCTYPE html>
          <html><head>
            <meta http-equiv="refresh" content="0; url=/" />
          </head><body>
            <p>Redirecting…</p>
          </body></html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./    # root now contains /<slug>/ for each client + index.html, assets/, 404.html, CNAME
          