# File: .github/workflows/deploy.yml
name: 🚀 Build & Deploy All Clients

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Build each client in project/
      - name: Build all clients
        run: |
          for dir in project/*/ ; do
            slug=$(basename "$dir")
            echo "🔨 Building $slug…"
            cd "$dir"
            npm ci
            npm run build
            cd ../../
            rm -rf "$slug"
            mkdir -p "$slug"
            cp -r "project/$slug/dist/." "$slug/"
          done

      # 4) Copy landing page into root (with absolute base='/')
      - name: Copy landing page
        run: |
          cp -r project/landingpage/dist/* .

      # 5) SPA fallback: serve index.html for all paths
      - name: Fallback 404 → index.html
        run: cp index.html 404.html

      # 6) Debug publish dir (just to confirm)
      - name: Show publish directory
        run: |
          echo "=== publish contents ==="
          ls -R .
          echo "========================"

      # 7) Deploy to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./   # contains index.html, assets/, /<slug>/, CNAME, 404.html
