# File: .github/workflows/deploy.yml
name: 🚀 Build & Deploy All Clients

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout code
      - uses: actions/checkout@v4

      # 2) Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3) Pre-normalize each project for GH Pages subfolders
      #    - Fix index.html to use relative paths
      #    - Ensure vite.config.* has base: '/<slug>/'
      - name: Pre-normalize projects
        shell: bash
        run: |
          set -e
          for dir in project/*/; do
            slug=$(basename "$dir")
            [ "$slug" = "landingpage" ] && continue
            echo "🧹 Normalizing: $slug"

            # A) Make index.html use relative paths
            if [ -f "$dir/index.html" ]; then
              sed -i 's|href="/vite.svg"|href="./vite.svg"|g' "$dir/index.html" || true
              sed -i 's|src="/src/main|src="./src/main|g' "$dir/index.html" || true
            fi

            # B) Ensure vite config has base '/<slug>/'
            cfg="$dir/vite.config.ts"
            [ -f "$dir/vite.config.js" ] && cfg="$dir/vite.config.js"
            if [ ! -f "$cfg" ] || ! grep -q "base: '/$slug/'" "$cfg"; then
              echo "✍️  Writing vite.config.ts with base '/$slug/'"
              printf "%s\n" \
                "import { defineConfig } from 'vite';" \
                "import react from '@vitejs/plugin-react';" \
                "" \
                "export default defineConfig({" \
                "  plugins: [react()], " \
                "  base: '/$slug/'," \
                "  optimizeDeps: { exclude: ['lucide-react'] }," \
                "});" > "$dir/vite.config.ts"
            fi
          done

      # 4) Build each client demo (skip landingpage)
      - name: Build demos
        shell: bash
        run: |
          set -e
          for dir in project/*/; do
            slug=$(basename "$dir")
            [ "$slug" = "landingpage" ] && continue

            echo "🔨 Considering demo: $slug"
            if [ ! -f "$dir/package.json" ]; then
              echo "➡️  Skipping $slug (no package.json)"
              continue
            fi

            echo "🔧 Installing deps for: $slug"
            cd "$dir"
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi

            echo "🏗  Building: $slug"
            # Try project's build script; if missing/fails, fall back to vite
            if npm run -s build; then
              echo "✅ Built with npm run build"
            else
              echo "ℹ️  Falling back to npx vite build for $slug"
              npx vite build
            fi

            cd ../../

            if [ -d "project/$slug/dist" ]; then
              rm -rf "$slug"
              mkdir -p "$slug"
              cp -r "project/$slug/dist/." "$slug/"
            else
              echo "⚠️  $slug built but no dist/ found — skipping copy"
            fi
          done

      # 5) Build & copy landing page into root
      - name: Build landing page
        shell: bash
        run: |
          cd project/landingpage
          npm ci
          npm run build
          cd ../../
          cp -r project/landingpage/dist/* .

      # 6) Dynamic SPA fallback for ALL paths (single-line echo, no template strings)
      - name: Create smart 404.html
        shell: bash
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="utf-8"><title>Redirecting</title></head><body><script>var p=location.pathname.split("/").filter(Boolean);if(p.length>0){var s=p[0];var r=p.slice(1).join("/");var h=r?"#/"+r:"";window.location.replace("/"+s+"/index.html"+h);}else{window.location.replace("/index.html");}</script><p>Redirecting...</p></body></html>' > 404.html

      # 7) Debug: list everything that will be published
      - name: Show publish directory
        shell: bash
        run: |
          echo "=== publish contents ==="
          ls -R .
          echo "========================"

      # 8) Deploy to GitHub Pages (gh-pages branch)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
