name: Deploy all projects to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build all projects
        run: |
          cd project/anissaylaa && npm ci && npm run build
          cd ../landingpage && npm ci && npm run build
          cd ../thairiverside && npm ci && npm run build
          cd ../chickenmacandmore && npm ci && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./__deploy
